name: teste_mesh
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get: ^4.6.6
  dio: ^5.4.3+1
  cloud_firestore: ^5.0.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  sqflite: ^2.3.3+1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:

  
  uses-material-design: true

 
  assets:
    - assets/images/mesh_logo.png
    - assets/images/line.png
    - assets/images/google_logo.png
    - assets/images/small_mesh_logo.png
    - assets/images/futbol.png
    - assets/images/delete_icon.png
    - assets/images/x_icon.png
    - assets/fonts/

 
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400 
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
